/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hly_learn_JNIUtil */

#ifndef _Included_com_hly_learn_JNIUtil
#define _Included_com_hly_learn_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hly_learn_JNIUtil
 * Method:    getFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hly_learn_JNIUtil_getFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
extern "C"
JNIEXPORT jstring