/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hly_learn_fragments_JniFragment */

#ifndef _Included_com_hly_learn_fragments_JniFragment
#define _Included_com_hly_learn_fragments_JniFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hly_learn_fragments_JniFragment
 * Method:    getFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hly_learn_fragments_JniFragment_getFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_hly_learn_fragments_JniFragment
 * Method:    setFromJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hly_learn_fragments_JniFragment_setFromJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
